### ISSUE TITLE
"mySalt" is not defined. (createLoginDataJs#3)

### ISSUE THREAD

**Issue by theotherp** [cbruegg/packetloss-watchdog#2]
Release v0.1.3

Script attempted a restart but got this error:
```
[2020-05-18T05:00:01.119661300] Could not restart router! Reason:
org.mozilla.javascript.EcmaError: ReferenceError: "mySalt" is not defined. (createLoginDataJs#3)
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4236)
        at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:4214)
        at org.mozilla.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:4304)
        at org.mozilla.javascript.ScriptRuntime.name(ScriptRuntime.java:1924)
        at org.mozilla.javascript.gen.createLoginDataJs_12._c_createLoginData_0(createLoginDataJs:3)
        at org.mozilla.javascript.gen.createLoginDataJs_12.call(createLoginDataJs)
        at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:412)
        at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3545)
        at org.mozilla.javascript.gen.createLoginDataJs_12.call(createLoginDataJs)
        at MainKt$restartRouterInternal$4.invokeSuspend(Main.kt:290)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:825)
```

Full log attached. Thank you.

[log.txt](https://github.com/cbruegg/packetloss-watchdog/files/4642552/log.txt)

**Comment by cbruegg** [comment]
Strange, seems like your router either performs encryption differently or not at all. Can you check what [this page](http://192.168.1.1/?status_status) says for you? For reference, here's what it looks like for me:

![grafik](https://user-images.githubusercontent.com/175421/82657793-421b5800-9c26-11ea-8762-761c62ddf066.png)

**Comment by theotherp** [comment]
See here:

<img width="368" alt="router" src="https://user-images.githubusercontent.com/14368889/82789104-053fa300-9e6a-11ea-92ac-5b851f2b4137.png">

https://github.com/diveflo/arris-tg3442-reboot seems to support my router. Perhaps you could take a look. Otherwise I'll may just run that script every night.
